spring:
  spring:
    security:
      oauth2:
        client:
          registration:
            pizza-admin-client:
              provider: pizzacloud
              client-id: pizza-admin-client
              client-secret: secret
              authorization-grant-type: authorization_code
              redirect-uri: "http://127.0.0.1:9090/login/oauth2/code/{registrationId}"
              scope: writeIngredients,deleteIngredients,openid
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema:
      - schema.sql
    data:
      - data-h2.sql
  sql:
    init:
      mode: always
      platform: h2
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    ru.zubov.pizzacloud: DEBUG
pizza:
  orders:
    pageSize: 10