spring:
  artemis:
    host: artemis.pizzacloud.com
    port: 61617
    user: admin
    password: admin
  application:
    name: SpringBoot-Multi-Environment
  profiles:
    active: @profileActive@
  data:
    rest:
      base-path: /data-api
  jpa:
    properties:
      hibernate:
        show_sql=true: true
        use_sql_comments: true
        format_sql: true
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false