spring:
  rabbitmq:
    host: rabbit.pizzacloud.com
    port: 5673
    username: admin
    password: admin
    template:
      exchange: pizzacloud.order
      routing-key: kitchens.central
      receive-timeout: 30000
  artemis:
    host: artemis.pizzacloud.com
    port: 61617
    user: admin
    password: admin
  kafka:
    bootstrap-servers:
#    - kafka.pizzacloud.com:9092
#    - kafka.pizzacloud.com:9093
#    - kafka.pizzacloud.com:9094
    - localhost:9092
  application:
    name: SpringBoot-Multi-Environment
  profiles:
    active: @profileActive@
  data:
    rest:
      base-path: /data-api
  jpa:
    properties:
      hibernate:
        show_sql=true: true
        use_sql_comments: true
        format_sql: true

#        для JSM
  jms:
    template:
      default-destination: pizzacloud.order.queue
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false