spring:
  security:
    oauth2:
        registration:
          pizza-admin-client:
            provider: pizzacloud
            client-id: pizza-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9090/login/oauth2/code/{registrationId}"
            scope: writeIngredients,deleteIngredients,openid
  application:
    name: SpringBoot-Multi-Environment
  profiles:
    active: @profileActive@
  data:
    rest:
      base-path: /data-api