spring:
  application:
    name: SpringBoot-Multi-Environment
  profiles:
    active: @profileActive@
logging:
  level:
    ru.zubov.pizzacloud: DEBUG
pizza:
  orders:
    pageSize: 10
---

#config test
spring:
  config:
    active:
      on-profile: test
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
      platform: h2
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
      schema:
        - schema.sql
      data:
        - data-h2.sql
  sql:
    init:
      mode: always
      platform: h2
  jpa:
    hibernate:
      ddl-auto: none
---

#config prod
spring:
  config:
    active:
      on-profile: prod
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema:
      - schema.sql
    data:
      - data-h2.sql
  sql:
    init:
      mode: always
      platform: h2
  jpa:
    hibernate:
      ddl-auto: none