spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
      platform: h2
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:
  sql:
    init:
      mode: always
      platform: h2
  jpa:
    hibernate:
      ddl-auto: none